### ISSUE TITLE
Creating groups for permissions

### ISSUE THREAD

**Issue by HandmadePrism** [bitpredator/bpt_menu#1]
Hello! How do I add permissions/groups? Thanks!

**Comment by bitpredator** [comment]
Hi, sorry for my late reply, you can create new groups in the config.lua file.

for example:

	{
		name = 'goto',
		label = _U('admin_goto_button'),
		groups = {'admin', 'mod', 'new_group'},
		command = function()
			local plyId = KeyboardInput('BPT_BOX_ID', _U('dialogbox_playerid'), '', 8)

			if plyId ~= nil then
				plyId = tonumber(plyId)
				
				if type(plyId) == 'number' then
					TriggerServerEvent('bpt_menu:Admin_BringS', GetPlayerServerId(PlayerId()), plyId)
				end
			end

			RageUI.CloseAll()
		end
	},

If you would like new roles and groups to be added for the whole community open a suggestion request
